#Makefile for src folder


arrays : arrays.cxx toolbox.cxx
	g++ -Wall -g -std=c++11 -o arrays arrays.cxx toolbox.cxx
	
mapnsum : map_n_sum.cxx toolbox.cxx
	g++ -Wall -g -std=c++11 -o mapnsum map_n_sum.cxx toolbox.cxx
	
cmpsrch : cmp_search.cxx toolbox.cxx
	g++ -Wall -g -std=c++11 -o cmpsrch cmp_search.cxx toolbox.cxx
	
tb : toolbox.cxx
	g++ -Wall -g -std=c++11 -o tb toolbox.cxx
	
