#Makefile for dev folder

mapping: mapping.cxx
	g++ -Wall -g -std=c++11 -o map mapping.cxx
	
t_search: t_search.cxx
	g++ -Wall -g -std=c++11 -o ts t_search.cxx
	
c_perm: c_perm.cxx
	g++ -Wall -g -std=c++11 -o cperm c_perm.cxx
	
b_perm: b_perm.cxx
	g++ -Wall -g -std=c++11 -o bperm b_perm.cxx
	
perm: perm.cxx
	g++ -Wall -g -std=c++11 -o perm perm.cxx
	
